on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Bump aur-weresocool
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup yarn
        run: npm install -g yarn

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile
      
      - name: Bumper Cool
        uses: ./src
        # if: "!contains(github.ref, '-')"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        with:
          base-branch: main
          formula-name: weresocool
          create-pullrequest: true
          pkgbuild-tap: xasopheno/aur-weresocool
          tag-name: ${{ steps.extract-version.outputs.tag-name }}
